name: Release and build installers

#on: [push, pull_request]
on: [workflow_dispatch]

jobs:

  build-windows-installer-msi:
    name: Build Installer on Windows (msi)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Create Windows Installer
        run: jpackage --type msi --name CloudlogSimpleLogger --app-version "1.2.6" --icon src/main/resources/static/cloudlog-simple-logger.png --win-menu --win-shortcut --input target/. --main-jar cloudlog-simple-logger-1.2.6.jar -d target/.

      - id: ls-files
        name: List files
        run: |
          dir target

      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          path: target/CloudlogSimpleLogger-1.2.6.msi
          name: windows-installer-msi
          retention-days: 1

  build-linux-installer:
    name: Build Installer on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Create Linux Installer
        run: jpackage -n CloudlogSimpleLogger --type deb --app-version "1.2.6" --icon src/main/resources/static/cloudlog-simple-logger.ico --linux-menu-group "HAM" --linux-shortcut -i target/. --main-jar cloudlog-simple-logger-1.2.6.jar -d target/.

      - id: ls-files
        name: List files
        run: |
          ls -al target

      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          path: target/cloudlogsimplelogger_1.2.6-1_amd64.deb
          name: linux-installer
          retention-days: 1


  build-runnable-jar:
    name: Build Runnable jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - id: ls-files
        name: List files
        run: |
          ls -al target

      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          path: target/cloudlog-simple-logger-1.2.6.jar
          name: runnable-jar
          retention-days: 1

  build-macos-installer:
    name: Build Installer on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Create macOS Installer
        run: jpackage --type dmg --name CloudlogSimpleLogger --app-version "1.2.6" --input target/. --main-jar cloudlog-simple-logger-1.2.6.jar -d target/.

      - id: ls-files
        name: List files
        run: |
          ls -al target

      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          path: target/CloudlogSimpleLogger-1.2.6.dmg
          name: macos-installer
          retention-days: 1


  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux-installer, build-windows-installer-msi, build-runnable-jar]
    steps:

      # DOWNLOAD INSTALLERS
      - id: download-linux-installer
        name: Download Linux installer
        uses: actions/download-artifact@v3
        with:
          name: linux-installer

      - id: download-windows-installer-msi
        name: Download Windows installer (msi)
        uses: actions/download-artifact@v3
        with:
          name: windows-installer-msi

      - id: download-runnable-jar
        name: Download Runnable jar
        uses: actions/download-artifact@v3
        with:
          name: runnable-jar

      - id: download-macos-installer
        name: Download MacOS installer (dmg)
        uses: actions/download-artifact@v3
        with:
          name: macos-installer

      - id: list-downloaded-files
        name: Rename downloaded files
        run: |
          ls -al 
          mv cloudlogsimplelogger_1.2.6-1_amd64.deb cloudlogsimplelogger_1.2.6.deb
          mv CloudlogSimpleLogger-1.2.6.msi cloudlogsimplelogger-1.2.6.msi
          mv CloudlogSimpleLogger-1.2.6.dmg cloudlogsimpleLogger-1.2.6.dmg
          ls -al

      # CREATE GITHUB RELEASE AND ADD ASSETS
      - id: tag
        name: Move example-release tag
        shell: bash
        if: false
        run: |
          # Move tag
          git tag -d 1.2.6
          git push --delete origin 1.2.6
          git tag -a 1.2.6 -m "First release 1.2.6"
          git push --follow-tags

      - id: create-release
        name: Create GitHub release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.2.6
          release_name: 1.2.6
          draft: false
          prerelease: false

      - name: Show env vars
        shell: bash
        run: |
          echo "GH_REPO: $GH_REPO"
          echo "GH_REPO_O: $GH_REPO_O"
          echo "GH_T: $GH_T"
          echo "URL: $URL"
        env:
          GH_REPO: ${{ github.repository }}
          GH_REPO_O: ${{ github.repository_owner }}
          GH_T: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ steps.create-release.outputs.upload_url }}

      - id: release-linux-installer
        name: Release Linux installer
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: cloudlogsimplelogger_1.2.6.deb
          asset_name: cloudlogsimplelogger_1.2.6.deb
          asset_content_type: application/x-binary

      - id: release-windows-installer-msi
        name: Release Windows installer (msi)
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: cloudlogsimplelogger-1.2.6.msi
          asset_name: cloudlogsimplelogger-1.2.6.msi
          asset_content_type: application/x-binary

      - id: release-runnable-jar
        name: Release Runnable jar
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: cloudlog-simple-logger-1.2.6.jar
          asset_name: cloudlog-simple-logger-1.2.6.jar
          asset_content_type: application/x-binary

      - id: release-macos-installer
        name: Release MacOs installer
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: cloudlogsimpleLogger-1.2.6.dmg
          asset_name: cloudlogsimpleLogger-1.2.6.dmg
          asset_content_type: application/x-binary

