name: Build Installers

on: [push, pull_request]

jobs:
  build-windows-installer:
    name: Build Installer on Windows (exe)
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: mvn package

    - name: Create Windows Installer
      run: jpackage --type exe --input target/. --name CloudlogSimpleLogger --main-jar cloudlog-simple-logger-1.1.0.jar -d target/.

    - id: ls-files
      name: List files
      run: |
        dir target

    - id: upload-installer
      name: Upload installer
      uses: actions/upload-artifact@v3
      with:
        path: target/CloudlogSimpleLogger-1.0.exe
        name: windows-installer
        retention-days: 1

  build-windows-installer-msi:
    name: Build Installer on Windows (msi)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Create Windows Installer
        run: jpackage --type msi --input target/. --name CloudlogSimpleLogger --main-jar cloudlog-simple-logger-1.1.0.jar -d target/.

      - id: ls-files
        name: List files
        run: |
          dir target

      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          path: target/CloudlogSimpleLogger-1.0.msi
          name: windows-installer-msi
          retention-days: 1

  build-linux-installer:
    name: Build Installer on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Create Linux Installer
        run: jpackage --type deb --input target/. --name CloudlogSimpleLogger --main-jar cloudlog-simple-logger-1.1.0.jar -d target/.

      - id: ls-files
        name: List files
        run: |
          ls -al target

      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          path: target/cloudlogsimplelogger_1.0-1_amd64.deb
          name: linux-installer
          retention-days: 1

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux-installer, build-windows-installer, build-windows-installer-msi]
    steps:

      # DOWNLOAD INSTALLERS
      - id: download-linux-installer
        name: Download Linux installer
        uses: actions/download-artifact@v3
        with:
          name: linux-installer

      - id: download-windows-installer
        name: Download Windows installer (exe)
        uses: actions/download-artifact@v3
        with:
          name: windows-installer

      - id: download-windows-installer-msi
        name: Download Windows installer (msi)
        uses: actions/download-artifact@v3
        with:
          name: windows-installer-msi


      - id: rename-downloaded-files
        name: Rename downloaded files
        run: |
          ls -al 
          mv cloudlogsimplelogger_1.0-1_amd64.deb cloudlogsimplelogger_1.1.deb
          mv CloudlogSimpleLogger-1.0.exe cloudlogsimplelogger-1.1.exe
          mv CloudlogSimpleLogger-1.0.msi cloudlogsimplelogger-1.1.msi
          ls -alR

      # CREATE GITHUB RELEASE AND ADD ASSETS
      - id: tag
        name: Move example-release tag
        shell: bash
        if: false
        run: |
          # Move tag
          git tag -d 1.1.0
          git push --delete origin 1.1.0
          git tag -a 1.0.0 -m "First release 1.1.0"
          git push --follow-tags

      - id: create-release
        name: Create GitHub release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.1.0
          release_name: 1.1.0
          draft: false
          prerelease: false

      - id: release-linux-installer
        name: Release Linux installer
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: cloudlogsimplelogger_1.1.deb
          asset_name: cloudlogsimplelogger_1.1.deb
          asset_content_type: application/x-binary

      - id: release-windows-installer-exe
        name: Release Windows installer (exe)
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: cloudlogsimplelogger-1.1.exe
          asset_name: cloudlogsimplelogger-1.1.exe
          asset_content_type: application/x-binary

      - id: release-windows-installer-msi
        name: Release Windows installer (msi)
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: cloudlogsimplelogger-1.1.msi
          asset_name: cloudlogsimplelogger-1.1.msi
          asset_content_type: application/x-binary