name: Build Installers

#on: [push, pull_request]
on: [workflow_dispatch]

jobs:
  build-windows-installer-msi:
    name: Build Installer on Windows (msi)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Create Windows Installer
        run: jpackage --type msi --name CloudlogSimpleLogger --app-version "1.1.0" --icon src/main/resources/static/cloudlog-simple-logger.png --win-console --win-menu --win-shortcut -input target/. --main-jar cloudlog-simple-logger-1.1.0.jar -d target/.

      - id: ls-files
        name: List files
        run: |
          dir target

      - id: upload-installer
        name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          path: target/CloudlogSimpleLogger-1.0.msi
          name: windows-installer-msi
          retention-days: 1

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-windows-installer-msi]
    steps:

      - id: download-windows-installer-msi
        name: Download Windows installer (msi)
        uses: actions/download-artifact@v3
        with:
          name: windows-installer-msi

      - id: rename-downloaded-files
        name: Rename downloaded files
        run: |
          ls -al 
          mv CloudlogSimpleLogger-1.0.msi cloudlogsimplelogger-1.1.msi
          ls -alR

      - id: release-windows-installer-msi
        name: Release Windows installer (msi)
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: cloudlogsimplelogger-1.1.msi
          asset_name: cloudlogsimplelogger-1.1.msi
          asset_content_type: application/x-binary